# Generated by Django 4.2.7 on 2026-02-03 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0002_assessment_assessmentversion_examinstance_and_more"),
        ("assessment_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("face_not_visible", "Face Not Visible"),
                            ("multiple_faces", "Multiple Faces Detected"),
                            ("tab_switch", "Tab/Window Switch"),
                            ("copy_paste", "Copy/Paste Detected"),
                            ("external_device", "External Device Detected"),
                            ("audio_anomaly", "Audio Anomaly"),
                            ("network_issue", "Network Connectivity Issue"),
                            ("suspicious_behavior", "Suspicious Behavior"),
                            ("system_integrity", "System Integrity Check"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("proctoring_session_id", models.CharField(max_length=255)),
                (
                    "event_data",
                    models.JSONField(help_text="Raw event data from proctoring system"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                ("screenshot_url", models.URLField(blank=True, null=True)),
                ("video_clip_url", models.URLField(blank=True, null=True)),
                ("audio_clip_url", models.URLField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_events",
                        to="assessment_core.attempt",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IntegrityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("under_review", "Under Review"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_violation", "No Violation Found"),
                            ("minor_violation", "Minor Violation"),
                            ("major_violation", "Major Violation"),
                            ("exam_invalidated", "Exam Invalidated"),
                            ("further_investigation", "Requires Further Investigation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "evidence_retention_until",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("evidence_deleted", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrity_incidents",
                        to="assessment_core.attempt",
                    ),
                ),
                (
                    "related_events",
                    models.ManyToManyField(
                        related_name="incidents", to="exam_integrity.integrityevent"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("incident_review", "Incident Review"),
                            ("escalation", "Escalation"),
                            ("appeal", "Appeal Process"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "required_reviewers",
                    models.JSONField(help_text="List of required reviewer roles/users"),
                ),
                (
                    "escalation_rules",
                    models.JSONField(
                        default=dict, help_text="Escalation conditions and actions"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(default="initial_review", max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=50, null=True)),
                ("decision_notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="exam_integrity.integrityincident",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("incident", "workflow_type")},
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("screenshot", "Screenshot"),
                            ("video", "Video Clip"),
                            ("audio", "Audio Clip"),
                            ("log", "System Log"),
                            ("network", "Network Capture"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("file_size", models.PositiveIntegerField()),
                (
                    "retention_policy",
                    models.CharField(default="standard", max_length=50),
                ),
                ("retention_until", models.DateTimeField()),
                ("auto_delete", models.BooleanField(default=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam_integrity.integrityevent",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="exam_integrity.integrityincident",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("event_count", "Event Count Threshold"),
                            ("event_pattern", "Event Pattern Matching"),
                            ("severity_weighted", "Severity Weighted Scoring"),
                            ("time_window", "Time Window Analysis"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("face_not_visible", "Face Not Visible"),
                            ("multiple_faces", "Multiple Faces Detected"),
                            ("tab_switch", "Tab/Window Switch"),
                            ("copy_paste", "Copy/Paste Detected"),
                            ("external_device", "External Device Detected"),
                            ("audio_anomaly", "Audio Anomaly"),
                            ("network_issue", "Network Connectivity Issue"),
                            ("suspicious_behavior", "Suspicious Behavior"),
                            ("system_integrity", "System Integrity Check"),
                            ("custom", "Custom Event"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("eq", "Equal"),
                            ("contains", "Contains"),
                            ("regex", "Regex Match"),
                        ],
                        max_length=20,
                    ),
                ),
                ("threshold_value", models.CharField(max_length=255)),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Additional rule parameters"
                    ),
                ),
                (
                    "base_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "score_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.CreateModel(
            name="ReviewStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_name", models.CharField(max_length=100)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("approval", "Approval"),
                            ("escalation", "Escalation"),
                            ("notification", "Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_role", models.CharField(blank=True, max_length=100)),
                ("instructions", models.TextField(blank=True)),
                ("required_actions", models.JSONField(default=list)),
                ("time_limit_hours", models.IntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("decision", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="exam_integrity.reviewworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "step_name"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="integrityincident",
            index=models.Index(
                fields=["tenant", "status", "risk_level"],
                name="exam_integr_tenant__399020_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrityincident",
            index=models.Index(
                fields=["attempt", "status"], name="exam_integr_attempt_0ebcf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrityevent",
            index=models.Index(
                fields=["tenant", "attempt", "event_type"],
                name="exam_integr_tenant__f296ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="integrityevent",
            index=models.Index(
                fields=["processed", "severity"], name="exam_integr_process_6543e0_idx"
            ),
        ),
    ]
