# Generated by Django 4.2.7 on 2026-02-03 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="RevokedToken",
            fields=[
                (
                    "jti",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("revoked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("builtin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("admin_contact", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("moodle_userid", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("attrs", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_pattern",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "allow"), ("deny", "deny")],
                        default="allow",
                        max_length=10,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.permission"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[("user", "user"), ("group", "group")], max_length=10
                    ),
                ),
                ("subject_id", models.UUIDField()),
                (
                    "resource_scope",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.role"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
            ),
        ),
        migrations.CreateModel(
            name="EmergencyAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_scope",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("justification", models.TextField()),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                (
                    "approval_method",
                    models.CharField(
                        choices=[("auto", "auto"), ("manual", "manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.permission"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_requests",
                        to="iam.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelegatedGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_scope",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("justification", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_delegations",
                        to="iam.user",
                    ),
                ),
                (
                    "granter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_delegations",
                        to="iam.user",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.permission"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=255)),
                ("resource", models.JSONField(blank=True, null=True)),
                ("prev_hash", models.CharField(blank=True, max_length=128, null=True)),
                ("hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iam.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttributePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[("simple", "simple"), ("opa", "opa")],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("expression", models.TextField()),
                (
                    "effect",
                    models.CharField(
                        choices=[("allow", "allow"), ("deny", "deny")],
                        default="allow",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rego", models.TextField(help_text="Rego source for OPA")),
                ("version", models.CharField(blank=True, max_length=64, null=True)),
                ("last_deployed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_deploy_status",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
