# Generated by Django 4.2.7 on 2026-02-03 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0002_assessment_assessmentversion_examinstance_and_more"),
        ("assessment_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeAuditLog",
            fields=[
                (
                    "auditlog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="iam.auditlog",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("grade_recorded", "Grade Recorded"),
                            ("conflict_detected", "Conflict Detected"),
                            ("conflict_resolved", "Conflict Resolved"),
                            ("grades_frozen", "Grades Frozen"),
                            ("amendment_requested", "Amendment Requested"),
                            ("amendment_approved", "Amendment Approved"),
                            ("workflow_started", "Workflow Started"),
                            ("workflow_completed", "Workflow Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("grade_related_resource", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "grade_audit_log",
            },
            bases=("iam.auditlog",),
        ),
        migrations.CreateModel(
            name="GradeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("auto_grader", "Auto Grader"),
                            ("manual", "Manual Grading"),
                            ("external", "External System"),
                            ("reconciliation", "Reconciliation Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("graded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_records",
                        to="assessment_core.attempt",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grade_integrity.gradesource",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt", "source")},
            },
        ),
        migrations.CreateModel(
            name="GradeFreeze",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frozen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("justification", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment_core.assessment",
                    ),
                ),
                (
                    "frozen_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("score_discrepancy", "Score Discrepancy"),
                            ("source_conflict", "Source Conflict"),
                            ("anomaly", "Statistical Anomaly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment_core.attempt",
                    ),
                ),
                (
                    "involved_records",
                    models.ManyToManyField(
                        related_name="conflicts", to="grade_integrity.graderecord"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amendment_type",
                    models.CharField(
                        choices=[
                            ("correction", "Correction"),
                            ("appeal", "Appeal"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("new_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("justification", models.TextField()),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendment_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="grade_integrity.graderecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("grade_amendment", "Grade Amendment"),
                            ("freeze_override", "Freeze Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.UUIDField()),
                ("required_approvers", models.JSONField()),
                ("current_step", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("approver_role", models.CharField(max_length=255)),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="grade_integrity.approvalworkflow",
                    ),
                ),
            ],
            options={
                "unique_together": {("workflow", "step_number")},
            },
        ),
    ]
