# Generated by Django 4.2.7 on 2026-02-04 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="response",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attempt",
            name="client_id",
            field=models.UUIDField(
                blank=True, help_text="Client-generated UUID for idempotency", null=True
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="client_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attempt",
            name="conflict_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="last_client_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="origin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attempt",
            name="server_version",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="response",
            name="client_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="response",
            name="client_ts",
            field=models.DateTimeField(
                blank=True, help_text="Client timestamp for the answer", null=True
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="response_hash",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_client_id", models.UUIDField(blank=True, null=True)),
                ("operation", models.CharField(max_length=20)),
                ("payload", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("client_ts", models.DateTimeField(blank=True, null=True)),
                ("client_id", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_client_id"],
                        name="assessment__resourc_12da51_idx",
                    )
                ],
            },
        ),
    ]
